spring:

  server:
    port: 8080

  datasource:
    url: jdbc:mysql://localhost:3306/todolist
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update   # create / create-drop / validate / none / update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    filter:
      dispatcher-types: REQUEST

app:
  jwt:
    secret: "change-this-to-a-256-bit-secret-at-least-32chars"
    expiration-ms: 3600000   # 1 ชม.